% BGSA code v1.0.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“ 'BGSA: Binary Gravitational Search Algorithm', Natural Computation, vol.9, pp.727- 745, 2010."
%
% This function calculates Gravitational constant. 
function G=BGconstant(iteration,max_it)

 G0=1;
 G=G0*(1-(iteration/max_it)); % eq.17.
