% BGSA code v1.0.
% Generated by Esmat Rashedi, 2010. 
% "	E. Rashedi, H. Nezamabadi-pour and S. Saryazdi,
%“ 'BGSA: Binary Gravitational Search Algorithm', Natural Computation, vol.9, pp.727- 745, 2010."
%
%This function updates the velocity and position of agents.
function [X,V]=Bmove(X,a,V)

%movement.
[N,n]=size(X);

V=rand(N,n).*V+a;

S=abs(tanh(V)); %eq. 13.

temp=rand(N,n)<S;
moving=find(temp==1);

X(moving)=~X(moving);   %eq. 14     